1.2.840.10008.1.2.4.80=jpeg-ls-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpegls.JpegLsLosslessImageReader::
1.2.840.10008.1.2.4.81=jpeg-ls-near-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpegls.JpegLsNearLosslessImageReader::
