1.2.840.10008.1.2.4.50=jpeg-ext:io.github.cocosip.dcm4che.imageio.codecs.jpeg.JpegImageReader::
1.2.840.10008.1.2.4.51=jpeg-ext:io.github.cocosip.dcm4che.imageio.codecs.jpeg.ExtendedJpegImageReader::
