1.2.840.10008.1.2.4.50=jpeg-ext:io.github.cocosip.dcm4che.imageio.codecs.jpeg.JpegImageWriter::
1.2.840.10008.1.2.4.51=jpeg-ext:io.github.cocosip.dcm4che.imageio.codecs.jpeg.ExtendedJpegImageWriter::
1.2.840.10008.1.2.4.57=jpeg-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg.LosslessJpegImageWriter::
1.2.840.10008.1.2.4.70=jpeg-lossless-sv1:io.github.cocosip.dcm4che.imageio.codecs.jpeg.LosslessJpegSv1ImageWriter::
