1.2.840.10008.1.2.4.90=jpeg2000-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LosslessImageReader::
1.2.840.10008.1.2.4.91=jpeg2000-lossy:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LossyImageReader::
1.2.840.10008.1.2.4.201=htj2k-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLosslessImageReader::
1.2.840.10008.1.2.4.202=htj2k-lossless-rpcl:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLosslessRpclImageReader::
1.2.840.10008.1.2.4.203=htj2k-lossy:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLossyImageReader::
