1.2.840.10008.1.2.4.90=jpeg2000-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LosslessImageWriter::
1.2.840.10008.1.2.4.91=jpeg2000-lossy:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LossyImageWriter::
1.2.840.10008.1.2.4.201=htj2k-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLosslessImageWriter::
1.2.840.10008.1.2.4.202=htj2k-lossless-rpcl:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLosslessRpclImageWriter::
1.2.840.10008.1.2.4.203=htj2k-lossy:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Htj2kLossyImageWriter::
