1.2.840.10008.1.2.4.90=jpeg2000-lossless:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LosslessImageWriter::
1.2.840.10008.1.2.4.91=jpeg2000-lossy:io.github.cocosip.dcm4che.imageio.codecs.jpeg2000.Jpeg2000LossyImageWriter::
